actors:
  konifar:
    image_url: /images/actors/konifar.jpg
    name: konifar
    url: https://twitter.com/konifar
  yome:
    image_url: /images/actors/yome.png
    name: yome
    url: https://twitter.com/konifar
  maetoo11:
    image_url: /images/actors/maetoo11.jpg
    name: maetoo11
    url: https://twitter.com/maetoo11
author: konifar
description: konifarとyome氏のゆるいpodcast
description_long: エンジニアのkonifarと専業主婦のyome氏が夫婦生活や仕事の話をゆるく話すpodcastです。
email: yahpeycoy0403@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: yomefm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/yome.fm/id1189585205
keywords: yomefm,konifar,嫁fm,こにふぁー
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: yome.fm
url: https://yomefm.github.io
